language: python

# Enumerate all Python/Django pairs until Travis has a real syntax for that
# Use tox -l to list available tox environments
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27-django111

  - python: 3.5
    env: TOXENV=py35-django111
  - python: 3.5
    env: TOXENV=py35-django20
  - python: 3.5
    env: TOXENV=py35-django21
  - python: 3.5
    env: TOXENV=py35-django22

  - python: 3.6
    env: TOXENV=py36-django111
  - python: 3.6
    env: TOXENV=py36-django20
  - python: 3.6
    env: TOXENV=py36-django21
  - python: 3.6
    env: TOXENV=py36-django22

  - python: 3.7
    env: TOXENV=py37-django111
  - python: 3.7
    env: TOXENV=py37-django20
  - python: 3.7
    env: TOXENV=py37-django21
  - python: 3.7
    env: TOXENV=py37-django22

  - python: 3.8
    env: TOXENV=py38-django22

install:
    - pip install tox-travis
    - pip install coveralls

script:
    - tox

sudo: false

after_success:
    coveralls
